### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Ryldjin** [mono300genuine/blablaland#1]
Comment désactiver le discord pour la l'inscription ou le setup je suis bloqué sur ça

**Comment by mono300genuine** [comment]
before I comment you, I'd like to hear about you.
where are you from and who are you?

**Comment by Ryldjin** [comment]
I'm French, and I've known blablaland for a long time, who I am ryldjin ^^

**Comment by mono300genuine** [comment]
oh, nice to meet you..
glad to see you on github.
how many years of experience in blablaland do you have?

**Comment by Ryldjin** [comment]
I'm playing the game in 2016, for nostagie I'd like to create a private server on it but I'm blocked from registering because of the discord.

**Comment by mono300genuine** [comment]
do you have another contact info
I am usally active on discord, telegram, skype, whatsapp.
I think using another contact method than github here is convienent for u.
what do you think about this?

**Comment by Ryldjin** [comment]
Telegram : https://t.me/neriox0

**Comment by mono300genuine** [comment]
👍
